# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28be973a8690e81ff2cc0180559c2b1c92b8727570144e98cdcbe945bfbe12db006151a94cf4d8c07da4c4591363e15fbb300187faeea5f38887e1da417a7189

test:
  secret_key_base: 71d1d0014c6262f43e3c792253e108fdd5ba5d3f952f20a683ad176c1cc79e95e927146ab5a661dcaadba8a42f18b7a2234f7bea567fefccdec4171b14d5a14e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
